"""
====================================================
BrainVisionAI
Footer Component
====================================================
"""

from datetime import datetime

from . import theme


class Footer:

    def __init__(

        self,

        canvas,

        model_name="EfficientNet-B0",

        accuracy="95.12%"

    ):

        self.canvas = canvas

        self.model = model_name

        self.accuracy = accuracy

    def draw(self):

        y = theme.PAGE_HEIGHT - theme.FOOTER_HEIGHT

        self.canvas.rectangle(

            0,

            y,

            theme.PAGE_WIDTH,

            theme.FOOTER_HEIGHT,

            theme.PRIMARY

        )

        self.canvas.text(

            35,

            y + 18,

            f"Model : {self.model}",

            theme.SMALL_FONT,

            theme.WHITE

        )

        self.canvas.text(

            430,

            y + 18,

            f"Best Accuracy : {self.accuracy}",

            theme.SMALL_FONT,

            theme.WHITE

        )

        self.canvas.text(

            960,

            y + 18,

            datetime.now().strftime(

                "%Y-%m-%d %H:%M"

            ),

            theme.SMALL_FONT,

            theme.WHITE

        )

        self.canvas.text(

            1370,

            y + 18,

            "Generated by BrainVisionAI",

            theme.SMALL_FONT,

            theme.WHITE

        )
