"""
====================================================
BrainVisionAI
Professional Footer
====================================================
"""

from datetime import datetime

from . import theme


class Footer:

    def __init__(

        self,

        canvas,

        model_name="BrainVisionAI",

        accuracy="95.12%"

    ):

        self.canvas = canvas

        self.model = model_name

        self.accuracy = accuracy

    # =================================================

    def draw(self):

        y = theme.PAGE_HEIGHT - theme.FOOTER_HEIGHT

        self.canvas.rectangle(

            0,

            y,

            theme.PAGE_WIDTH,

            theme.FOOTER_HEIGHT,

            theme.PRIMARY

        )

        # ---------------------------------------------
        # Left
        # ---------------------------------------------

        self.canvas.text(

            60,

            y + 28,

            f"AI Model : {self.model}",

            theme.SMALL_FONT,

            theme.WHITE

        )

        # ---------------------------------------------
        # Center Left
        # ---------------------------------------------

        self.canvas.text(

            760,

            y + 28,

            f"Validation Accuracy : {self.accuracy}",

            theme.SMALL_FONT,

            theme.WHITE

        )

        # ---------------------------------------------
        # Center Right
        # ---------------------------------------------

        self.canvas.text(

            1760,

            y + 28,

            datetime.now().strftime(

                "%Y-%m-%d %H:%M"

            ),

            theme.SMALL_FONT,

            theme.WHITE

        )

        # ---------------------------------------------
        # Right
        # ---------------------------------------------

        self.canvas.text(

            2550,

            y + 28,

            "Generated by BrainVisionAI",

            theme.SMALL_FONT,

            theme.WHITE

        )

        # ---------------------------------------------
        # Copyright
        # ---------------------------------------------

        self.canvas.text(

            60,

            y + 62,

            "Research Prototype • Not intended to replace clinical judgment.",

            theme.TINY_FONT,

            (225,225,225)

        )
